# All passwords are set to the word secret
#username: admin
#password_hash: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
admin: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
syfret: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
brackenfell: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
ceres: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
swellendam: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
montagu: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
bredasdorp: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
caledon: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
worcester: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
polkadraai: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
somerset west: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
kraaifontein: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
grabouw: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
malmesbury: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
piketberg: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
vredendal: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
dedoorns: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
springbok: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
airport: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
laingsburg: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
carbon: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
khayelitsha: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
spine: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
beaufort Wes: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
george: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
riversdal: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
ladysmith: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
plettenbergbaai: $2a$10$48o.VBcdNfZHXkMxsk0gpubxHKNWbKdAqgaF3O4hISnDTG8WoTL7K
